spring.application.name=bff-relatorio

server.port=8085

ms1.url=http://localhost:8080
ms2.url=http://localhost:8081
ms3.url=http://localhost:8082

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html